### ISSUE TITLE
Latest (as NOMIS)

### ISSUE THREAD

**Issue by paulb20** [olihawkins/statxplorer#1]
Is there a sensible way to tweak the json query to replicate the NOMIS API which includes the Latest keyword? I guess the obvious is to manually edit the json file if I'm downloading a time series - which is usually as I (may) want to pipe into seasonal package. 

I guess it would be feasible to do something with regexes, but that maybe beyond me.

I think if the DWP json has no date you always get the latest, but time series are useful.

**Comment by olihawkins** [comment]
If I remember it right, if you don't specify a date you get data for **all the dates**, and that can be problematic because you can run into a limit on the the maximum number of records the API will return for a single query.

It's very hard to solve this problem at the package level, because the package handles sending queries and processing the results, rather than constructing the queries themselves. 

To get the data for the latest period you need to know the name of the latest period in the dataset you are working with, because unlike Nomis the Stat-Xplore API doesn't offer the latest period for a dataset as an abstract parameter.

The way I have handled this in the past is to first send a query that gets all of the periods available for the dataset in question, and then send further queries using that information. That might mean getting the data for the latest period, or getting data for each of the periods you are interested in, sending a different query for each period so as to stay under the API limits.

To get this to work in practice you need to create two queries. The first is a simple query for all the periods in the dataset. The second is a template query where the date condition contains a placeholder that you replace with the string for a different period each time you call the query.

You don't need complicated regexs to do this. Create a query that will get the data you need for a single period, download the json, then replace the period name with the string `<date_id>` and save the file. When you want to call the query for a given period, load the file and replace the placeholder with the actual period name using:

```r
query <- stringr::str_replace(query_template, "<date_id>", period_name)
```

If you need to incorporate date-based logic in selecting the periods for which you want to request data, it helps to write a function for translating the periods as they are represented in Stat-Xplore into Date objects in R, and vice-versa. Annoyingly, this translation depends on how the periods are represented in the dataset in question: this differs between datasets.

None of this is ideal but then Stat-Xplore is not the most user-friendly API for official data. However, I am open to suggestions for ways the package could make this sort of thing easier.
